version: '3.7'

services:
  noipy:
    image: dotslashme/noipy
    command: "/bin/sh -c 'while :; do python /noipy.py; sleep 5m & wait $${!}; done;'"
    restart: on-failure
    environment:
      - NOIP_HOSTS=domain1.tld,domain2.tld
    secrets:
      - noip-username
      - noip-password
